baseURL = "https://olivierchemla.xyz"
languageCode = "en-us"
title = "Pulsar"
theme = "pulsar"
DefaultContentLanguage = "fr"


[author]
  name = "Olivier Chemla"
  homepage = "olivierchemla.com"

[menu]

    [[menu.main]]
    name = "Acceuil"
    url = "/"
    weight= 1

    [[menu.main]]
    name = "Projets"
    url = "/projects"
    weight= 2

    [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight= 3

    [[menu.social]]
    name = "Linkedin"
    pre = '<i class="fab fa-linkedin"></i>'
    url = "https://www.linkedin.com/in/olivier-chemla-86a261106/"
    weight= 1

    [[menu.social]]
    name = "GitHub"
    pre = '<i class="fab fa-github"></i>'
    url = "https://github.com/OliveCh12"
    weight= 2

    [[menu.social]]
    name = "CodePen"
    pre = '<i class="fab fa-codepen"></i>'
    url = "https://codepen.io/SweetPerception/"
    weight= 3

    [[menu.social]]
    name = "Facebook"
    pre = '<i class="fab fa-facebook-f"></i>'
    url = "/"
    weight= 3

    [[menu.social]]
    name = "Instagram"
    pre = '<i class="fab fa-instagram"></i>'
    url = "https://www.instagram.com/olivierchemla/"
    weight= 4

[params]

[params.hero]
description = "Freelancer, Étudiant autodidacte passionné de graphisme et de nouvelles technologies depuis très jeune. Je suis quelqu'un qui aime se challenger désirant aller plus loin et d'en apprendre toujours plus. À l'affût des nouvelles tendances et ouvert à toutes formes de création graphique, c'est l'une des raisons qui me motive créer et m'adapter selon chaque projet. Perfectionniste dans ma démarche, je saurais apporter une réponse à la hauteur des attentes de chaque demandes."
#--------------------
# Skills Area Section
#--------------------
[params.section_skills]
enable = true
title = "Mes_Benchmarks"
subtitle = "Mes compétences, mon niveau, mes acquis."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
button = "Plus de détails"

[[params.skills]]
name = "HTML"
description ="Bases solides et bonne compréhension de la structure d'une page HTML"
value = "80"
pre = "fab fa-html5"

[[params.skills]]
name = "CSS / SASS"
description ="Bases solides et bonne compréhension de la structure d'une page HTML"
value = "70"
pre = "fab fa-css3-alt"


[[params.skills]]
name = "Javascript (ES7)"
description ="Bases solides et bonne compréhension de la structure d'une page HTML"
value = "50"
pre = "fab fa-js-square"
[[params.skills]]
name = "ReactJS"
description ="Bases solides et bonne compréhension de la structure d'une page HTML"
value = "40"
pre = "fab fa-react"

[[params.skills]]
name = "VueJS"
description ="Bonne bases dans l'enssemble"
value = "70"
pre = "fab fa-vuejs"

[[params.skills]]
name = "JAMStack (Static Gen)"
description ="A l'aise dans l'utilisation de générateur de site statique (Jekyll, Hugo, GatsbyJS)"
value = "50"
pre = "fas fa-feather"


[[params.skills_details]]
title = "Languages"
list = ["Javascript (ES6)", "PHP", "Bash", "SCSS", "Python"]
info = "Working"
[[params.skills_details]]
title = "Framework (Front / Back)"
list = ["Bootstrap", "ReactJS", "Hugo", "Jeckyll", "Laravel"]
info = "working"

[[params.skills_details]]
title = "Autres"
list = ["Shell", "Unix", "Vim", "Photoshop", "Illustrator", "Sketch", "GitHub"]
info = "working"