baseURL = "https://olivierchemla.xyz"
languageCode = "en-us"
title = "Front-End Developper"
theme = "pulsar"
DefaultContentLanguage = "fr"

[taxonomies]
  category = "categories"
  tag = "tags"


[author]
  name = "Olivier Chemla"
  homepage = "olivierchemla.com"

[menu]

    [[menu.main]]
    name = "Acceuil"
    url = "/"
    weight= 1

    [[menu.main]]
    name = "Projets"
    url = "/projects"
    weight= 2

    [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight= 3

    [[menu.social]]
    name = "Linkedin"
    pre = '<i class="fab fa-linkedin"></i>'
    url = "https://www.linkedin.com/in/olivier-chemla-86a261106/"
    weight= 1

    [[menu.social]]
    name = "GitHub"
    pre = '<i class="fab fa-github"></i>'
    url = "https://github.com/OliveCh12"
    weight= 2

    [[menu.social]]
    name = "CodePen"
    pre = '<i class="fab fa-codepen"></i>'
    url = "https://codepen.io/SweetPerception/"
    weight= 3

    [[menu.social]]
    name = "Facebook"
    pre = '<i class="fab fa-facebook-f"></i>'
    url = "/"
    weight= 3

    [[menu.social]]
    name = "Instagram"
    pre = '<i class="fab fa-instagram"></i>'
    url = "https://www.instagram.com/olivierchemla/"
    weight= 4

[params]

[params.hero]
description = "Salut ! Enchanté, moi, c'est Olivier, je suis Étudiant en Développement Web sur Paris, mais aussi Autodidacte ! Peut être même plus autodidacte que étudiant finalement...;)  On peut dire que je suis de nature curieuse si bien que j'adore me challenger, et par conséquent, j'essaye de rester en pépetuelle évolution ! Même si c'est dur... Pour plus d'information n'hésitez pas à me contacter. Ah oui, je suis indécis sur la couleur de mon site donc dites moi celle qui conviendrais le mieux. Merci !"
#--------------------
# Skills Area Section
#--------------------
[params.section_skills]
enable = true
title = "Mes_Benchmarks"
subtitle = "Mes compétences, mon niveau, mes acquis."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
button = "Plus de détails"

[[params.skills]]
name = "HTML"
description ="Bases solides et bonne compréhension de la structuration d'une page HTML"
value = "90"
pre = "fab fa-html5"

[[params.skills]]
name = "CSS / SCSS"
description ="Bonnes notions, structuration du CSS à l'aide de BEM et du préprocesseur SASS"
value = "70"
pre = "fab fa-css3-alt"


[[params.skills]]
name = "Javascript (ES7)"
description ="Bonne maîtrise de Javascript en PureJS/VanillaJS (En constant apprentissage)"
value = "60"
pre = "fab fa-js-square"

[[params.skills]]
name = "VueJS"
description ="Maitrisé dans l'enssemble, déjà utilisé sur plusieurs projets."
value = "60"
pre = "fab fa-vuejs"

[[params.skills]]
name = "ReactJS"
description ="Concepts de bases assimilés (En apprentissage)"
value = "40"
pre = "fab fa-react"


[[params.skills]]
name = "JAMStack (Static Gen)"
description ="A l'aise dans l'utilisation de générateur de site statique (Jekyll, Hugo, GatsbyJS)"
value = "70"
pre = "fas fa-feather"


[[params.skills_details]]
title = "Languages / Library"
list = ["Javascript (ES7)", "jQuery", "PHP", "Bash", "SCSS", "Python"]
info = "Working"
[[params.skills_details]]
title = "Frameworks (Front / Back)"
list = ["Bootstrap", "VueJS", "ReactJS (Junior)", "Hugo", "Jeckyll", "Laravel"]
info = "working"

[[params.skills_details]]
title = "Autres"
list = ["NPM / Yarn", "NPM Scripts / Gulp", "GitHub / GitLab", "Shell", "Linux", "VSCode / Atom / Vim", "Photoshop", "Illustrator", "Sketch / Figma"]
info = "working"